#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=32gb,walltime=14:00:00
#PBS -N trekker

mkdir -p output

t1=$(jq -r .t1 config.json)

time singularity exec -e docker://brainlife/pydeface:2.0 pydeface $t1 --force --outfile output/t1.nii.gz --verbose
